import json, subprocess, time, os, sys

def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True, shell=True)
    return r.stdout.strip(), r.stderr.strip(), r.returncode

# ── STEP 1: CLOSE ALL BROKEN PRs FROM saurabhhhcodes ─────────────────────────
print("=== STEP 1: Closing broken PRs ===")
stdout, _, _ = run('gh pr list --limit 300 --state open --json number,author --jq "[.[] | select(.author.login==\\"saurabhhhcodes\\") | .number]"')
pr_nums = json.loads(stdout) if stdout else []
print(f"Found {len(pr_nums)} broken PRs to close")

close_msg = """Hi @saurabhhhcodes, thank you for your interest in contributing to this project! 🙏

Unfortunately, after carefully reviewing this PR, we found that the changes contain **syntax errors and malformed code** that would break the application if merged. For example:
- Invalid arrow function syntax (missing parameter in `.catch()`)  
- Code placed outside of React component scope  
- Incomplete or misplaced statements

These appear to be auto-generated fixes that are not compatible with our codebase structure.

We are closing this PR to keep the repository clean and stable. If you'd like to contribute:
1. **Fork** the repository and clone it locally
2. **Identify** a specific bug or issue to fix
3. **Test** your changes locally before submitting
4. **Open a PR** with a clear description of what was fixed and why

We truly appreciate your enthusiasm and look forward to a well-crafted contribution in the future! 🚀"""

with open("close_msg.txt", "w", encoding="utf-8") as f:
    f.write(close_msg)

for num in pr_nums:
    print(f"  Closing PR #{num}")
    run(f'gh pr comment {num} --body-file close_msg.txt')
    run(f'gh pr close {num}')
    time.sleep(0.8)

print(f"Closed {len(pr_nums)} broken PRs\n")


# ── STEP 2: PROCESS ALL OPEN ISSUES ──────────────────────────────────────────
print("=== STEP 2: Processing all open issues ===")

RESPONSES = {
    72: """Hi @TomHacker69, great feature request! Comparing a resume to a LinkedIn profile is a real pain point for job seekers.\n\n**Implementation Plan:**\n1. **LinkedIn Data Ingestion** — Allow users to upload a LinkedIn PDF export\n2. **Text Extraction** — Extend NLP pipeline to parse LinkedIn PDF\n3. **Comparison Engine** — Diff skills, experience, education, summary, certifications\n4. **UI Layer** — Side-by-side comparison view with highlighted discrepancies\n5. **Report Export** — Downloadable PDF/CSV inconsistency report\n\n**Files to create/modify:**\n- `backend/routers/linkedin.py` (new)\n- `backend/ml_pipeline/linkedin_parser.py` (new)\n- `frontend/src/components/LinkedInComparison.jsx` (new)\n\nAssigning to you — looking forward to your PR! 🚀""",
    71: """Hi @TomHacker69, excellent idea! A structured dashboard will give users an at-a-glance view of resume completeness.\n\n**Implementation Plan:**\n1. **Backend** — `/checklist` endpoint scoring: Contact, Skills, Education, Experience, Projects, Certifications\n2. **Scoring Logic** — Return completeness per section (present/partial/missing)\n3. **Frontend** — `ResumeChecklist.jsx` with progress rings per section\n4. **Dashboard Integration** — Embed in the analysis results page\n\n**Files:**\n- `backend/routers/analyze.py` — extend response\n- `frontend/src/components/ResumeChecklist.jsx` (new)\n\nAssigning to you! 💪""",
    70: """Hi @TomHacker69, love this idea! Recruiters spend only ~7 seconds on a resume — a strong AI summary is a game changer.\n\n**Implementation Plan:**\n1. **Prompt Engineering** — Design a Gemini/OpenAI prompt for a 3-sentence recruiter summary\n2. **Backend** — `POST /summary` → `{headline, skills_highlight, experience_overview, copy_text}`\n3. **Frontend** — `RecruiterSummary.jsx` with a Copy to Clipboard button\n4. **Loading State** — Shimmer loader during AI generation\n\n**Files:**\n- `backend/routers/summary.py` (new)\n- `frontend/src/components/RecruiterSummary.jsx` (new)\n\nAssigning to you — this will wow users! 🌟""",
    69: """Hi @TomHacker69, a history timeline is a must-have!\n\n**Implementation Plan:**\n1. **DB Schema** — `resume_analyses` table: `(id, user_id, resume_name, score, created_at, analysis_json)`\n2. **Backend** — `GET /history` (paginated) and `GET /history/{id}`\n3. **Timeline UI** — `AnalysisTimeline.jsx` with vertical timeline\n4. **Version Compare** — Side-by-side diff of two analyses\n5. **Delete/Search** — Allow users to delete entries and search by date\n\n**Files:**\n- `backend/database.py` — new table migration\n- `backend/routers/history.py` (new)\n- `frontend/src/components/AnalysisTimeline.jsx` (new)\n\nAssigning to you! 🔥""",
    68: """Hi @TomHacker69, this is a great differentiator! Most analyzers miss soft skills entirely.\n\n**Implementation Plan:**\n1. **Soft Skills Dictionary** — Curate 50+ soft skills (leadership, communication, teamwork...)\n2. **NLP Detection** — spaCy + keyword matching + sentence-level context\n3. **Confidence Scoring** — Rate each detection (high/medium/low)\n4. **Gap Recommendations** — Compare vs role-specific expected soft skills\n5. **Frontend** — `SoftSkillsReport.jsx` with categorized chips and confidence badges\n\n**Files:**\n- `backend/ml_pipeline/soft_skills.py` (new)\n- `frontend/src/components/SoftSkillsReport.jsx` (new)\n\nAssigning to you! 🎯""",
    67: """Hi @TomHacker69, benchmarking is a brilliant feature!\n\n**Implementation Plan:**\n1. **Benchmark Dataset** — Role-specific benchmark metrics (avg skills, experience years, section completeness)\n2. **Comparison Logic** — Score user resume against benchmark percentiles\n3. **Visualization** — Radar/bar chart with Recharts\n4. **Backend** — `GET /benchmark?role=<role>` endpoint\n5. **Frontend** — `BenchmarkChart.jsx`\n\nAssigning to you! 🚀""",
    66: """Hi @TomHacker69, targeted evaluations are very powerful!\n\n**Implementation Plan:**\n1. **Industry Profiles** — Rubrics for Tech, Finance, Healthcare, Marketing, etc.\n2. **Keyword Bank** — Industry-specific must-have keywords and skills\n3. **Scoring Engine** — Score resume against selected industry profile\n4. **UI** — Industry selector dropdown + industry-specific score breakdown\n5. **Recommendations** — Tailored suggestions per industry\n\n**Files:**\n- `backend/data/industry_profiles.json` (new)\n- `backend/ml_pipeline/industry_evaluator.py` (new)\n- `frontend/src/components/IndustryEvaluation.jsx` (new)\n\nAssigning to you! 🌍""",
    65: """Hi @TomHacker69, great idea — layout matters for ATS and readability!\n\n**Implementation Plan:**\n1. **PDF Structure Analysis** — Use `pdfminer` to detect font sizes, whitespace, column count, section headers\n2. **Layout Scoring** — Check consistent formatting, margins, bullets, header hierarchy\n3. **ATS Compatibility** — Flag tables, graphics, columns that confuse ATS\n4. **Frontend** — `LayoutAnalyzer.jsx` with issue list and score gauge\n\n**Files:**\n- `backend/ml_pipeline/layout_analyzer.py` (new)\n- `frontend/src/components/LayoutAnalyzer.jsx` (new)\n\nAssigning to you! 🎨""",
    64: """Hi @TomHacker69, readability is often overlooked — great call!\n\n**Implementation Plan:**\n1. **Readability Metrics** — Flesch-Kincaid, Gunning Fog, sentence length analysis\n2. **Backend** — Extend `/analyze` to return readability scores\n3. **Visual Insights** — Highlight overly complex sentences in the resume preview\n4. **Score Gauge** — Show a readability dial (Easy/Medium/Hard)\n5. **Recommendations** — Suggest simpler alternatives for flagged sentences\n\n**Files:**\n- `backend/ml_pipeline/readability.py` (new)\n- `frontend/src/components/ReadabilityScore.jsx` (new)\n\nAssigning to you! ✨""",
    63: """Hi @TomHacker69, a personalized action plan is the perfect closing feature!\n\n**Implementation Plan:**\n1. **AI Prompt** — After analysis, call the LLM: "Given these resume weaknesses, generate a prioritized 5-step action plan"\n2. **Structured Response** — `[{step, priority, description, estimated_time}]`\n3. **Action Plan UI** — `ActionPlan.jsx` with numbered steps, priority badges, checkboxes\n4. **Progress Tracking** — Let users mark steps done and save progress\n5. **Backend** — `POST /action-plan` endpoint\n\nAssigning to you — this will be the standout feature! 🌟""",
    62: """Hi @TomHacker69, a history dashboard will give users long-term value!\n\n**Implementation Plan:**\n1. **Data Aggregation** — Aggregate past analyses: average score, score trend, most improved sections\n2. **Dashboard UI** — Score trend line chart, section improvement bars, resume count badge\n3. **Backend** — `GET /dashboard/stats` endpoint\n4. **Filters** — Filter by date range and resume type\n\nAssigning to you! 📈""",
    61: """Hi @TomHacker69, multilingual support opens the tool to a global audience!\n\n**Implementation Plan:**\n1. **Language Detection** — `langdetect` to identify resume language\n2. **Translation Layer** — Optionally translate to English before analysis\n3. **i18n UI** — `react-i18next` for UI language switching\n4. **Localized Analysis** — Language-specific keyword banks\n5. **Language Badge** — Show detected language in report\n\nAssigning to you! 🌐""",
    60: """Hi @TomHacker69, keyword density is critical for ATS optimization!\n\n**Implementation Plan:**\n1. **Keyword Extraction** — TF-IDF + spaCy to rank keywords by density\n2. **Density Map** — Top 20 keywords with frequency bars\n3. **ATS Overlap** — Compare against job description keywords if provided\n4. **Stuffing Warning** — Flag excessively repeated keywords\n5. **Frontend** — Word cloud + frequency table\n\nAssigning to you! 🔍""",
    59: """Hi @TomHacker69, exporting to PDF is highly requested!\n\n**Implementation Plan:**\n1. **Backend PDF Generation** — Use `fpdf2` to generate a branded PDF report\n2. **Report Structure** — Overall score, section scores, keyword analysis, recommendations\n3. **Download Endpoint** — `GET /report/{id}/pdf` → stream PDF\n4. **Frontend** — "Download Report" button with loading state\n5. **Branding** — Add project logo and colors to PDF\n\nAssigning to you! 📄""",
    58: """Hi @TomHacker69, a writing checklist guides users before they even upload!\n\n**Implementation Plan:**\n1. **Checklist Items** — 20+ best-practice items (action verbs, quantified achievements, no photos...)\n2. **Interactive UI** — Grouped checkboxes (Content, Format, ATS, Tone)\n3. **Completion Score** — Show % completed as users tick items\n4. **Pre-Upload Flow** — Show checklist before upload\n5. **Persistence** — Save state to localStorage\n\nAssigning to you! 📝""",
    57: """Hi @TomHacker69, tracking improvement over time is very motivating!\n\n**Implementation Plan:**\n1. **Score History** — Store each analysis score with timestamp\n2. **Progress Chart** — Line chart showing score evolution\n3. **Milestones** — Celebrate improvements with notifications\n4. **Section Heatmap** — Show which sections improved/declined\n5. **Goal Setting** — Let users set a target score and track progress\n\nAssigning to you! 🏆""",
    56: """Hi @TomHacker69, section completeness analysis gives users clear direction!\n\n**Implementation Plan:**\n1. **Section Detector** — NLP to detect all standard sections\n2. **Completeness Score** — Missing/Minimal/Good/Excellent per section\n3. **Missing Section Alerts** — Warn users about absent sections\n4. **Content Quality** — Detect placeholder text, very short descriptions\n5. **Frontend** — Section grid with quality indicators\n\nAssigning to you! 📊""",
    55: """Hi @TomHacker69, skill gap analysis is one of the most valuable features we could add!\n\n**Implementation Plan:**\n1. **JD Parser** — Accept job description text alongside resume\n2. **Skill Extraction** — Extract required skills from JD using NLP\n3. **Gap Detection** — Missing, Partial, Present classification\n4. **Priority Ranking** — Rank missing skills by frequency in similar postings\n5. **Frontend** — Venn-diagram-style visualization\n\n**Files:**\n- `backend/ml_pipeline/skill_gap.py` (new)\n- `frontend/src/components/SkillGapAnalysis.jsx` (new)\n\nAssigning to you — flagship feature! 🌟""",
    54: """Hi @TomHacker69, an ATS breakdown is exactly what job seekers need!\n\n**Implementation Plan:**\n1. **ATS Simulation** — Simulate Taleo, Workday, Greenhouse parsers\n2. **Breakdown Scores** — Keyword match, Formatting, Section headers, Font compatibility\n3. **Issue List** — Ranked ATS-breaking issues with fix instructions\n4. **Dashboard UI** — Score donut chart + issue cards\n5. **Tips** — ATS-specific optimization tips per issue\n\n**Files:**\n- `backend/ml_pipeline/ats_simulator.py` (new)\n- `frontend/src/components/ATSDashboard.jsx` (new)\n\nAssigning to you — this will be huge! 🚀""",
    53: """Hi @prince-pokharna, this is an important maintenance issue! You are absolutely correct.\n\n**Recommended Fix:**\n1. **Remove model.pkl from git** — `git rm --cached backend/model.pkl` + add `*.pkl` to `.gitignore`\n2. **Add model generation script** — `backend/scripts/train_model.py` to train and save locally\n3. **CI Integration** — `setup.sh` step that trains the model if `model.pkl` is missing\n4. **OR Model Registry** — Upload to GitHub Releases/cloud bucket + add download script\n\n**Files to modify:**\n- `.gitignore` — add `*.pkl`\n- `backend/scripts/train_model.py` (new)\n- `README.md` — add setup instructions\n\nAssigning to you — great catch! 🎯""",
    52: """Hi @prince-pokharna, rate limiting is critical for production stability!\n\n**Recommended Implementation:**\n1. **Install** — `pip install slowapi`\n2. **Global Limiter** — Add `Limiter` to `main.py`\n3. **Per-Endpoint Limits:**\n   - `POST /analyze` → 10 req/min per IP\n   - `POST /ai-*` endpoints → 5 req/min per IP\n   - Auth endpoints → 20 req/min per IP\n4. **Custom Error** — `HTTP 429` with `Retry-After` header\n5. **Auth Users** — Higher limits for logged-in users\n\n**Files:**\n- `backend/main.py` — add `slowapi` middleware\n- `backend/routers/analyze.py` — add `@limiter.limit()` decorators\n- `backend/requirements.txt` — add `slowapi`\n\nAssigning to you — essential for production! 🚀""",
    51: """Hi @prince-pokharna, excellent security catch! Both issues could expose sensitive user data.\n\n**Fix 1 — SQLite File:**\n- Add `*.sqlite`, `*.db` to `.gitignore` immediately\n- Use env var for DB path: `DB_PATH=./data/user_db.sqlite`\n- In production, use PostgreSQL via `DATABASE_URL`\n\n**Fix 2 — JWT Secret:**\n```\n# .env.example\nJWT_SECRET=CHANGE_ME_USE_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS\n```\nAdd startup validation:\n```python\nif settings.JWT_SECRET in (\"\", \"CHANGE_ME\", \"secret\"):\n    raise RuntimeError(\"JWT_SECRET must be set to a strong secret!\")\n```\n\n**Files:**\n- `.gitignore`\n- `.env.example`\n- `backend/main.py` — add startup secret validation\n\nAssigning to you — please prioritize this! 🛡️""",
    50: """Hi @NiranjanRSoorej06, a scroll-to-top button is a great UX improvement!\n\n**Implementation:**\n```jsx\nconst ScrollToTop = () => {\n  const [visible, setVisible] = useState(false);\n  useEffect(() => {\n    const onScroll = () => setVisible(window.scrollY > 300);\n    window.addEventListener('scroll', onScroll);\n    return () => window.removeEventListener('scroll', onScroll);\n  }, []);\n  return visible ? (\n    <button onClick={() => window.scrollTo({top:0, behavior:'smooth'})}\n      className="scroll-to-top" aria-label="Scroll to top">↑</button>\n  ) : null;\n};\n```\n\n**Files:**\n- `frontend/src/components/ScrollToTop.jsx` (new)\n- `frontend/src/App.jsx` — add `<ScrollToTop />` globally\n- `frontend/src/index.css` — add button styles\n\nAssigning to you — quick and impactful win! 🎯""",
    49: """Hi @NiranjanRSoorej06, thanks for catching this! A wrong favicon creates brand inconsistency.\n\n**Fix:**\n1. Check `frontend/public/favicon.ico` and `frontend/index.html`\n2. Replace with the correct favicon file\n3. Add both formats:\n```html\n<link rel="icon" type="image/svg+xml" href="/favicon.svg" />\n<link rel="icon" type="image/x-icon" href="/favicon.ico" />\n```\n4. Add `apple-touch-icon.png` for iOS\n\n**Files:**\n- `frontend/public/favicon.ico` — replace\n- `frontend/index.html` — update link tags\n\nAssigning to you! ✅""",
    48: """Hi @durdana3105, configurable training parameters are essential for reproducibility!\n\n**Implementation:**\n1. **Config File** — `backend/config/training_config.yaml` with all hyperparameters\n2. **Config Loader** — `backend/ml_pipeline/config_loader.py` to parse YAML\n3. **CLI Args** — Accept config path as CLI arg to `train_model.py`\n4. **Env Override** — Allow env vars to override config values\n5. **Logging** — Log all training params at start of every run\n\nAssigning to you! 🔧""",
    47: """Hi @durdana3105, caching encoded feature templates is a smart performance optimization!\n\n**Implementation:**\n1. **Cache Layer** — `functools.lru_cache` or `joblib.Memory`\n2. **Cache Invalidation** — Invalidate on model version change\n3. **Benchmark** — Timing decorator to measure latency before/after\n4. **Redis Option** — For production, optionally use Redis backend\n5. **Tests** — Unit tests verifying cache hits/misses\n\nAssigning to you! ⚡""",
    46: """Hi @durdana3105, validating model artifacts on load is critical for reliability!\n\n**Implementation:**\n1. **Schema Validation** — Store `model_metadata.json` with expected features, version, creation date\n2. **Load-time Check** — Verify pkl matches metadata (feature count, model class)\n3. **Hash Verification** — SHA-256 hash of model file; verify on load\n4. **Graceful Failure** — Clear `ModelValidationError` with actionable message\n5. **Logging** — Log model version and validation status on startup\n\nAssigning to you! 🛡️""",
    45: """Hi @durdana3105, model versioning is crucial as the project evolves!\n\n**Implementation:**\n1. **Version Scheme** — Semantic versioning (e.g., `v1.2.0`) for model files\n2. **Metadata Store** — `model_registry.json`: version, accuracy, training date, feature list\n3. **Version API** — `GET /model/version` endpoint\n4. **Migration Script** — Promote a new model version to production\n5. **Rollback** — Keep last 2 versions with rollback script\n\nAssigning to you! 📦""",
    44: """Hi @durdana3105, context managers for DB connections are a Python best practice!\n\n**Implementation:**\n```python\nfrom contextlib import contextmanager\n\n@contextmanager\ndef get_db():\n    conn = sqlite3.connect(DB_PATH)\n    try:\n        yield conn\n        conn.commit()\n    except Exception:\n        conn.rollback()\n        raise\n    finally:\n        conn.close()\n```\n\n**Files:**\n- `backend/database.py` — add context manager\n- All router files — use `with get_db() as db:`\n\nAssigning to you! 🔧""",
    43: """Hi @durdana3105, proper transaction management and error logging are essential!\n\n**Implementation:**\n1. **Transaction Wrapper** — Wrap multi-step DB ops in explicit transactions\n2. **Rollback on Error** — Catch exceptions, rollback, re-raise with context\n3. **Structured Logging** — Use Python `logging` module (not `print`)\n4. **DB Error Handler** — Global FastAPI exception handler for `sqlite3.DatabaseError`\n5. **Audit Log** — Log all write operations with user ID and timestamp\n\nAssigning to you! 📝""",
    42: """Hi @durdana3105, a proper migration system will save a lot of headaches!\n\n**Implementation:**\n1. **Choose a Tool** — Use `Alembic` (recommended) or `yoyo-migrations`\n2. **Initial Migration** — Generate migration for current schema\n3. **Migration Runner** — Run migrations on app startup automatically\n4. **Version Table** — Track applied migrations in `schema_migrations` table\n5. **CI Check** — CI step verifying migrations are up-to-date\n\nAssigning to you! 🗃️""",
    41: """Hi @durdana3105, adding indexes is a quick win for query performance!\n\n**Implementation:**\n```sql\nCREATE INDEX IF NOT EXISTS idx_users_email ON users(email);\nCREATE INDEX IF NOT EXISTS idx_analyses_user_id ON resume_analyses(user_id);\nCREATE INDEX IF NOT EXISTS idx_analyses_created ON resume_analyses(created_at);\n```\n\n1. **Audit Queries** — Identify most frequent query patterns\n2. **Add Indexes** — On `users.email`, `users.id`, `resume_analyses.user_id`, `resume_analyses.created_at`\n3. **Benchmark** — Use `EXPLAIN QUERY PLAN` to verify index usage\n\nAssigning to you! ⚡""",
    40: """Hi @durdana3105, a TROUBLESHOOT.md is often the most-read file in an open source project!\n\n**Suggested Structure:**\n```\n# Troubleshooting Guide\n## Common Installation Issues\n## Backend Issues (port in use, DB errors, model not found)\n## Frontend Issues (Vite proxy, CORS)\n## Docker Issues\n## CI/CD Issues\n## Getting Help\n```\n\n**Files:**\n- `TROUBLESHOOT.md` (new, root of repo)\n- `README.md` — add link to TROUBLESHOOT.md\n\nAssigning to you — this will save dozens of contributor hours! 🙏""",
    27: """Hi @kumudasrip, replacing mock data with real integrations is a high-impact improvement!\n\n**Implementation:**\n1. **GitHub API** — `GET /users/{username}/repos` for repo count, stars, forks\n2. **Activity** — `GET /users/{username}/events` for commit activity\n3. **Token Management** — Store GitHub token as env var (never in frontend)\n4. **Rate Limit Handling** — Respect GitHub's 60/5000 req/hr limits\n5. **Caching** — Cache GitHub data for 15 minutes\n\n**Files:**\n- `backend/routers/github_analytics.py` (new)\n- `backend/utils/github_client.py` (new)\n- `frontend/src/components/GitHubStats.jsx` — replace mock data\n\nAssigning to you! 🔗""",
    26: """Hi @kumudasrip, robust upload validation is critical for reliability!\n\n**Implementation:**\n1. **File Size Limit** — Max 5MB in both frontend and backend\n2. **MIME Type Check** — Verify `content_type == "application/pdf"`\n3. **PDF Integrity** — Use `PyPDF2` to validate the PDF\n4. **Password Protection** — Detect and reject encrypted PDFs\n5. **Structured Errors** — `{error: "FILE_TOO_LARGE", message: "...", max_size_mb: 5}`\n6. **Frontend UX** — Specific error messages, not generic "Upload failed"\n\n**Files:**\n- `backend/utils/file_validator.py` (new)\n- `frontend/src/components/InputForm.jsx` — add client-side validation\n\nAssigning to you! 🛡️""",
    25: """Hi @kumudasrip, great catch! This is a classic Python gotcha that causes nasty bugs in production.\n\n**The Problem:**\n```python\n# BAD — the list is shared across all instances\nclass InterviewRequest(BaseModel):\n    topics: List[str] = []\n```\n\n**The Fix:**\n```python\nfrom pydantic import BaseModel, Field\nclass InterviewRequest(BaseModel):\n    topics: List[str] = Field(default_factory=list)\n```\n\nSearch for all occurrences:\n```bash\ngrep -rn "= \\[\\]" backend/\ngrep -rn "= {}" backend/\n```\nFix each with `Field(default_factory=list)` / `Field(default_factory=dict)`.\n\nAssigning to you — please fix urgently! 🚨""",
    24: """Hi @kumudasrip, this is a real blocker bug — thanks for reporting it!\n\n**Root Cause:**\nThe in-app resume builder submits a different field name than what `/analyze` expects.\n\n**Diagnose:**\n1. Check `backend/routers/analyze.py` — what field name does it expect? (e.g., `file: UploadFile = File(...)`)\n2. Check the builder's submit function — what field name is used in `FormData`?\n\n**Quick Fix:**\n```python\n# Accept both field names\nasync def analyze(\n    file: UploadFile = File(None),\n    resume: UploadFile = File(None),\n):\n    upload = file or resume\n    if not upload:\n        raise HTTPException(400, "No file uploaded")\n```\n\nOr fix the frontend: `formData.append('file', builderFile, 'resume.pdf')`\n\nAssigning to you — this affects core functionality! 🚨""",
    15: """Hi @Prashant-Singh-Rawat, the forgot password flow is an essential auth feature!\n\n**Implementation Plan:**\n1. **Backend — Request Reset:** `POST /auth/forgot-password` → generate secure token → send email via SendGrid/SMTP\n2. **Backend — Reset Password:** `POST /auth/reset-password` → validate token → hash new password → save\n3. **Frontend — Forgot Password Page:** Email input form → "Check your email" success state\n4. **Frontend — Reset Password Page:** New password + confirm → redirect to login on success\n5. **Security:** Rate-limit forgot-password endpoint (3 req/hour per email)\n\n**Files:**\n- `backend/routers/auth.py` — two new endpoints\n- `backend/utils/email_sender.py` (new)\n- `frontend/src/pages/ForgotPasswordPage.jsx` (new)\n- `frontend/src/pages/ResetPasswordPage.jsx` (new)\n- `frontend/src/App.jsx` — add new routes\n\nAssigning to you! 🔐""",
    3: """Hi @durdana3105, trust-building sections are crucial for user conversion!\n\n**Implementation Plan:**\n1. **FAQ Section** — Accordion with 8-10 common questions about the tool\n2. **Reviews/Testimonials** — Carousel with 3-5 testimonials with star ratings\n3. **Trust Badges** — "10,000+ Resumes Analyzed", "Open Source", "AI-Powered"\n4. **Stats Counter** — Animated number counter\n5. **CTA Banner** — Strong call-to-action above the footer\n\n**Files:**\n- `frontend/src/components/FAQ.jsx` (new)\n- `frontend/src/components/Testimonials.jsx` (new)\n- `frontend/src/components/TrustBadges.jsx` (new)\n- `frontend/src/pages/Home.jsx` — integrate sections\n\nAssigning to you! ✨""",
    2: """Hi @Taranpreet-codes, upgrading to semantic BERT embeddings is a fantastic technical improvement!\n\n**Implementation Plan:**\n```python\nfrom sentence_transformers import SentenceTransformer, util\nmodel = SentenceTransformer('all-MiniLM-L6-v2')\nresume_emb = model.encode(resume_text)\njd_emb = model.encode(job_description)\nsimilarity = util.cos_sim(resume_emb, jd_emb)\n```\n\n1. **Library** — `sentence-transformers` (already in requirements)\n2. **Hybrid Scoring** — Semantic (60%) + keyword match (40%)\n3. **Section-Level** — Embed each section separately for granular scoring\n4. **Performance** — Cache embeddings per resume; `@lru_cache` on model load\n5. **Benchmarking** — Compare new vs old scores on a test set\n\n**Files:**\n- `backend/ml_pipeline/semantic_matcher.py` (new)\n- `backend/ml_pipeline/predictor.py` — integrate\n- `backend/tests/test_semantic_matcher.py` (new)\n\nAssigning to you — this is a high-value technical contribution! 🏆"""
}

stdout, _, _ = run('gh issue list --limit 100 --state open --json number,title,author')
issues = json.loads(stdout) if stdout else []
print(f"Processing {len(issues)} issues...")

for issue in issues:
    num = issue['number']
    author = issue['author']['login']
    title = issue['title']
    
    msg = RESPONSES.get(num)
    
    if not msg:
        msg = f"""Hi @{author}, thank you for this contribution to the project! 🙏

Your issue **"{title}"** has been reviewed and looks like a valuable addition.

**Next Steps:**
1. Make sure you're working from the latest `main` branch
2. Create a feature branch: `git checkout -b feature/<short-description>`
3. Implement your changes with proper tests
4. Open a PR referencing this issue: `Closes #{num}` in your PR description

Feel free to ask questions in the comments if you need guidance. Looking forward to your contribution! 🚀"""
    
    print(f"  Issue #{num}: {title[:55]}")
    with open("issue_msg.txt", "w", encoding="utf-8") as f:
        f.write(msg)
    run(f'gh issue comment {num} --body-file issue_msg.txt')
    run(f'gh issue edit {num} --add-assignee {author}')
    time.sleep(1)

print(f"\nDone processing {len(issues)} issues")
print("All tasks completed!")

# cleanup
for f in ["close_msg.txt", "issue_msg.txt", "temp_issue_msg.txt", "temp_pr_msg.txt", "pr_msg.txt", "msg68.txt", "msg69.txt", "msg70.txt", "msg71.txt", "msg72.txt"]:
    try:
        os.remove(f)
    except:
        pass
